services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    networks:
      - digital-wallet-micro-services_default

  mongo:
    image: mongo:7.0
    restart: always
    hostname: mongo
    command: --bind_ip_all --replSet rs0
    env_file:
      - .env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - digital-wallet-micro-services_default

  mongo-init:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./infra/db/scripts/init-mongo.js:/scripts/init-mongo.js:ro
    command: mongosh --host mongo:27017 /scripts/init-mongo.js
    networks:
      - digital-wallet-micro-services_default

  mongo-express:
    image: mongo-express:1.0.2-18
    restart: always
    ports:
      - 8082:8082
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    networks:
      - digital-wallet-micro-services_default

volumes:
  mongodb_data:

networks:
  digital-wallet-micro-services_default:
    external: true