services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongodb/mongodb-community-server:7.0.9-ubuntu2204
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --username root --password example --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.2-18
    restart: always
    ports:
      - 8082:8082
    env_file:
      - mongo_express.env
  rabbitMQ:
    image: rabbitmq:4.0
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - rabbit.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
