services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - digital-wallet-micro-services_default
  db:
    image: postgres:15.10-alpine
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
    - ./infra/db/migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digital-wallet-micro-services_default
volumes:
  wallet-data:

networks:
  digital-wallet-micro-services_default:
    external: true